from .affine import (
    affine_hidden_branch_reversal,
    guarded_fibre_dominance,
    staged_affine_hidden_elimination,
    tower_affine_hidden_elimination,
    variable_precision_affine_hidden_reduction,
)
from .adapted import (
    closure_adapted_observer,
    closure_scores,
    compare_observers,
    leakage_channels,
    observer_from_subspace,
    simple_spectrum_closure_certificate,
    whitened_perturbation,
)
from .batch import batch_map
from .bridge import dv_bridge
from .connection import (
    connection_current,
    fixed_observer_coordinates,
    forcing_from_current,
    observer_transition,
    reconstruct_precision_from_fixed_observer_coordinates,
)
from .core import (
    canonical_lift,
    hidden_projector,
    local_visible_calculus,
    visible_geometry,
    visible_precision,
)
from .empirical_kernel_jet import extract_sparse_kn_jet
from .ensemble import (
    ceiling_mediated_local_quadratic_ensemble,
    coordinate_local_quadratic_ensemble,
    intrinsic_local_quadratic_ensemble,
)
from .evidence import dispatch_evidence, dispatch_singular_evidence, local_evidence, local_evidence_from_hessian
from .extract import SupervisedGeometry, extract_supervised, extract_covariance
from .kernel_reduction import (
    PolynomialJet,
    ReducedKernelActionDatum,
    reduce_kernel_action,
    reduce_kernel_action_kn,
)
from .exceptions import BatchTaskError, InputValidationError, NomogeoError, SupportError
from .field import (
    classify_support_event_from_jet,
    clock_rate,
    comparison_envelope_bounds,
    default_hidden_complement,
    hidden_load_from_pi,
    interval_hessian_at_exact_family,
    kernel_schur_jet_from_coefficients,
    lambda_rhs,
    local_coupled_birth,
    pi_from_hidden_load,
    pi_rhs,
    restart_hidden_load_birth,
    restart_hidden_load_death,
    sampled_interval_closure_check,
    sampled_interval_leakage,
    sampled_interval_stationarity,
    semisimple_event_block,
    support_stratum_transport,
)
from .frontier import (
    declared_frontier_local_certificate,
    declared_ladder_dimension_cost_intervals,
    exact_branch_hessian,
    general_graph_frontier_hessian,
    weighted_family_frontier_scores,
)
from .hidden import (
    canonical_hidden_realisation,
    clock,
    hidden_load,
    hidden_contraction,
    inverse_visible_class,
    load_from_hidden_contraction,
    minimal_hidden_realisation,
    transport_hidden_load,
    visible_from_hidden_load,
)
from .perturbation import rank_k_covariance_perturbation, rank_one_covariance_perturbation, residual_margin_ordering
from .regime import classify_from_hessian, classify_regime
from .singular import classify_singular_kernel
from .singular_types import (
    BranchChannelDatum,
    BranchChannelTemplate,
    CriticalBranchTemplate,
    SingularClassification,
    SingularRegimeKind,
    UnresolvedKernelJetRefusal,
    WeightedHomogeneousTemplate,
)
from .slice import (
    active_face_restriction,
    reduce_local_chart,
    transverse_complement,
)
from .source import (
    CaptureCurveResult,
    EvidenceDecompositionResult,
    InformationBudgetResult,
    ObserverDiagnosticsResult,
    SourceLawResult,
    capture_curve,
    evidence_decomposition,
    information_budget,
    observer_diagnostics,
    source_law,
)
from .steer import (
    ObserverScoreResult,
    OptimizeResult,
    SteerResult,
    optimize_observer,
    score_observer,
    steer,
)
from .regime_types import (
    ConeKind,
    ConeSpec,
    EvidenceResult,
    JacobianConvention,
    OrbitSpec,
    QuadraticKernelSeed,
    ReducedKernelDatum,  # deprecated alias → QuadraticKernelSeed
    ReducedLocalDatum,
    RegimeClassification,
    RegimeKind,
    RegularCone,
    RegularEvidenceTemplate,
    RegularInterior,
    RegularQuotient,
    RegularQuotientCone,
    SingularEvidenceTemplate,
    TowerEliminationRecord,
    TowerStageRecord,
    UnresolvedEvidenceRefusal,
    UnresolvedKernel,
    IndefiniteStationaryPoint,
    UnsupportedConeReduction,
    UnsupportedEvidenceRefusal,
)
from .quotient import (
    gaussian_bhattacharyya_distance,
    gaussian_data_processing_contraction,
    gaussian_forward_kl,
    gaussian_hellinger_squared,
    gaussian_reverse_kl,
    observed_covariance,
    observer_collapse_descends,
)
from .types import (
    AffineHiddenBranchReversalResult,
    AffineHiddenReductionResult,
    AffineHiddenStageResult,
    ClosureAdaptedObserverResult,
    ClosureScoresResult,
    CeilingMediatedLocalQuadraticEnsembleResult,
    ConnectionCurrentResult,
    CoordinateLocalQuadraticEnsembleResult,
    DVBridgeResult,
    DeclaredFrontierLocalCertificateResult,
    DeclaredLadderDimensionCostResult,
    ExactBranchHessianResult,
    FixedObserverCoordinatesResult,
    GeneralGraphFrontierHessianResult,
    GaussianContractionResult,
    GuardedFibreDominanceResult,
    HiddenLoadResult,
    IntrinsicLocalQuadraticEnsembleResult,
    IntervalHessianResult,
    KernelJetResult,
    LeakageChannelsResult,
    LinearAlgebraMetadata,
    LocalCalculusResult,
    LocalCoupledBirthResult,
    ObserverComparisonResult,
    ObserverTransitionResult,
    RealisationResult,
    RankKCovariancePerturbationResult,
    RankOneCovariancePerturbationResult,
    ResidualMarginResult,
    SampledIntervalLeakageResult,
    SemisimpleEventBlockResult,
    SimpleSpectrumClosureCertificateResult,
    SupportRestartResult,
    SupportStratumTransportResult,
    VisibleGeometryResult,
    WeightedFamilyFrontierResult,
)
from .validation import Tolerances

__version__ = "0.4.0"

# ── Frozen surfaces (2026-04-13) ──────────────────────────────────────
# The following functions are validated by the nomoselect benchmark suite
# (Iris, Wine, Breast Cancer, Golub, SRBCT) and must not change signature
# or semantics without re-running those benchmarks:
#
#   closure_adapted_observer   – subspace selection (commuting_exact mode)
#   closure_scores             – leakage / visible / eta diagnostics
#   compare_observers          – pairwise dominance certificates
#   declared_ladder_dimension_cost_intervals – task-aware rank phase diagram
#   whitened_perturbation      – H^{-1/2} Delta H^{-1/2}
#   affine_hidden_branch_reversal          – model ranking with fibre volume
#   variable_precision_affine_hidden_reduction – exact Gaussian fibre reduction
#   guarded_fibre_dominance    – fibre vs variational norm diagnostic
#
# Result types consumed by nomoselect:
#   ClosureAdaptedObserverResult, ClosureScoresResult,
#   ObserverComparisonResult, DeclaredLadderDimensionCostResult
# ──────────────────────────────────────────────────────────────────────

__all__ = [
    "AffineHiddenBranchReversalResult",
    "AffineHiddenReductionResult",
    "AffineHiddenStageResult",
    "BranchChannelDatum",
    "BranchChannelTemplate",
    "BatchTaskError",
    "CeilingMediatedLocalQuadraticEnsembleResult",
    "ClosureAdaptedObserverResult",
    "ClosureScoresResult",
    "CriticalBranchTemplate",
    "ConeKind",
    "ConeSpec",
    "ConnectionCurrentResult",
    "CoordinateLocalQuadraticEnsembleResult",
    "DVBridgeResult",
    "DeclaredFrontierLocalCertificateResult",
    "DeclaredLadderDimensionCostResult",
    "EvidenceResult",
    "ExactBranchHessianResult",
    "FixedObserverCoordinatesResult",
    "GaussianContractionResult",
    "GeneralGraphFrontierHessianResult",
    "GuardedFibreDominanceResult",
    "HiddenLoadResult",
    "InputValidationError",
    "IntrinsicLocalQuadraticEnsembleResult",
    "IntervalHessianResult",
    "JacobianConvention",
    "KernelJetResult",
    "LeakageChannelsResult",
    "LinearAlgebraMetadata",
    "LocalCalculusResult",
    "LocalCoupledBirthResult",
    "NomogeoError",
    "PolynomialJet",
    "ObserverComparisonResult",
    "ObserverTransitionResult",
    "OrbitSpec",
    "RankKCovariancePerturbationResult",
    "RankOneCovariancePerturbationResult",
    "RealisationResult",
    "QuadraticKernelSeed",
    "ReducedKernelDatum",  # deprecated alias
    "ReducedKernelActionDatum",
    "ReducedLocalDatum",
    "RegimeClassification",
    "RegimeKind",
    "RegularCone",
    "RegularEvidenceTemplate",
    "RegularInterior",
    "RegularQuotient",
    "RegularQuotientCone",
    "ResidualMarginResult",
    "SingularClassification",
    "SingularEvidenceTemplate",
    "SingularRegimeKind",
    "SampledIntervalLeakageResult",
    "SemisimpleEventBlockResult",
    "SimpleSpectrumClosureCertificateResult",
    "SupervisedGeometry",
    "SupportError",
    "SupportRestartResult",
    "SupportStratumTransportResult",
    "Tolerances",
    "TowerEliminationRecord",
    "TowerStageRecord",
    "UnresolvedEvidenceRefusal",
    "UnresolvedKernelJetRefusal",
    "UnresolvedKernel",
    "IndefiniteStationaryPoint",
    "UnsupportedConeReduction",
    "UnsupportedEvidenceRefusal",
    "VisibleGeometryResult",
    "WeightedFamilyFrontierResult",
    "WeightedHomogeneousTemplate",
    "__version__",
    "affine_hidden_branch_reversal",
    "batch_map",
    "canonical_hidden_realisation",
    "canonical_lift",
    "capture_curve",
    "CaptureCurveResult",
    "ceiling_mediated_local_quadratic_ensemble",
    "active_face_restriction",
    "classify_from_hessian",
    "classify_regime",
    "classify_singular_kernel",
    "classify_support_event_from_jet",
    "clock",
    "clock_rate",
    "closure_adapted_observer",
    "closure_scores",
    "compare_observers",
    "comparison_envelope_bounds",
    "connection_current",
    "coordinate_local_quadratic_ensemble",
    "default_hidden_complement",
    "declared_frontier_local_certificate",
    "declared_ladder_dimension_cost_intervals",
    "dispatch_evidence",
    "dispatch_singular_evidence",
    "dv_bridge",
    "evidence_decomposition",
    "EvidenceDecompositionResult",
    "extract_sparse_kn_jet",
    "exact_branch_hessian",
    "extract_covariance",
    "extract_supervised",
    "fixed_observer_coordinates",
    "forcing_from_current",
    "gaussian_bhattacharyya_distance",
    "gaussian_data_processing_contraction",
    "gaussian_forward_kl",
    "gaussian_hellinger_squared",
    "gaussian_reverse_kl",
    "general_graph_frontier_hessian",
    "guarded_fibre_dominance",
    "hidden_contraction",
    "hidden_load",
    "information_budget",
    "InformationBudgetResult",
    "hidden_load_from_pi",
    "hidden_projector",
    "interval_hessian_at_exact_family",
    "intrinsic_local_quadratic_ensemble",
    "inverse_visible_class",
    "kernel_schur_jet_from_coefficients",
    "lambda_rhs",
    "leakage_channels",
    "load_from_hidden_contraction",
    "local_coupled_birth",
    "local_evidence",
    "local_evidence_from_hessian",
    "local_visible_calculus",
    "minimal_hidden_realisation",
    "observed_covariance",
    "observer_collapse_descends",
    "observer_diagnostics",
    "ObserverDiagnosticsResult",
    "ObserverScoreResult",
    "optimize_observer",
    "OptimizeResult",
    "observer_from_subspace",
    "observer_transition",
    "pi_from_hidden_load",
    "pi_rhs",
    "rank_k_covariance_perturbation",
    "reduce_kernel_action",
    "reduce_kernel_action_kn",
    "reduce_local_chart",
    "rank_one_covariance_perturbation",
    "reconstruct_precision_from_fixed_observer_coordinates",
    "residual_margin_ordering",
    "restart_hidden_load_birth",
    "restart_hidden_load_death",
    "sampled_interval_closure_check",
    "sampled_interval_leakage",
    "sampled_interval_stationarity",
    "semisimple_event_block",
    "simple_spectrum_closure_certificate",
    "score_observer",
    "source_law",
    "SourceLawResult",
    "staged_affine_hidden_elimination",
    "steer",
    "SteerResult",
    "support_stratum_transport",
    "tower_affine_hidden_elimination",
    "transverse_complement",
    "transport_hidden_load",
    "variable_precision_affine_hidden_reduction",
    "visible_from_hidden_load",
    "visible_geometry",
    "visible_precision",
    "weighted_family_frontier_scores",
    "whitened_perturbation",
]
